// Old sample products for reference
export const sampleProducts = [
  {
    id: 1,
    code: "TCV01",
    name: "Terma solar completa de 6 tubos (60L) de acero inox 316 interno + acero galbanizado pintado externo; Ø58×1800 mm",
    otherNames: "- Terma Solar de 60L Tapa Verde\n- Terma Solar de 6 Tubos Tapa Verde",
    fotos: "",
    description:
      "- Termotanque + Caja de Tubos + Estructura\n- Termotanque de acero inox 316 interno y acero galvanizado pintado externo\n- Termotanque no presurizado\n- Aislante térmico de poliuretano entre el tanque interno y externo\n- Estructura de acero inoxidable\n- Sin boya (tanque auxiliar)",
    price: "1,080.00",
    otherPrices: "1,000.00",
    notes: "- Se requiere de boya cuando no tiene tanque elevado (Rotoplas)\n- El precio normal es con boya\n- El otro precio es sin boya",
    stock: 5,
    category: "Termas Solares",
  },
  {
    id: 2,
    code: "TCV02",
    name: "Terma solar completa de 8 tubos (80L) de acero inox 316 interno + acero galbanizado pintado externo; Ø58×1800 mm",
    otherNames: "- Terma Solar de 80L Tapa Verde\n- Terma Solar de 8 Tubos Tapa Verde",
    fotos: "",
    description:
      "- Termotanque + Caja de Tubos + Estructura\n- Termotanque de acero inox 316 interno y acero galvanizado pintado externo\n- Termotanque no presurizado\n- Aislante térmico de poliuretano entre el tanque interno y externo\n- Estructura de acero inoxidable",
    price: "1,280.00",
    otherPrices: "1,200.00",
    notes: "- Se requiere de boya cuando no tiene tanque elevado (Rotoplas)\n- El precio normal es con boya\n- El otro precio es sin boya",
    stock: 8,
    category: "Termas Solares",
  },
  {
    id: 3,
    code: "TCV03",
    name: "Terma solar completa de 10 tubos (100L) de acero inox 316 interno + acero galbanizado pintado externo; Ø58×1800 mm",
    otherNames: "- Terma Solar de 100L Tapa Verde\n- Terma Solar de 10 Tubos Tapa Verde",
    fotos: "",
    description:
      "- Termotanque + Caja de Tubos + Estructura\n- Termotanque de acero inox 316 interno y acero galvanizado pintado externo\n- Termotanque no presurizado\n- Aislante térmico de poliuretano entre el tanque interno y externo\n- Estructura de acero inoxidable",
    price: "1,430.00",
    otherPrices: "1,350.00",
    notes: "- Se requiere de boya cuando no tiene tanque elevado (Rotoplas)\n- El precio normal es con boya\n- El otro precio es sin boya",
    stock: 12,
    category: "Termas Solares",
  },
  {
    id: 4,
    code: "TCV04",
    name: "Terma solar completa de 12 tubos (120L) de acero inox 316 interno + acero galbanizado pintado externo; Ø58×1800 mm",
    otherNames: "- Terma Solar de 120L Tapa Verde\n- Terma Solar de 12 Tubos Tapa Verde",
    fotos: "",
    description:
      "- Termotanque + Caja de Tubos + Estructura\n- Termotanque de acero inox 316 interno y acero galbanizado pintado externo\n- Termotanque no presurizado\n- Aislante térmico de poliuretano entre el tanque interno y externo\n- Estructura de acero inoxidable",
    price: "1,580.00",
    otherPrices: "1,500.00",
    notes: "- Se requiere de boya cuando no tiene tanque elevado (Rotoplas)\n- El precio normal es con boya\n- El otro precio es sin boya",
    stock: 6,
    category: "Termas Solares",
  },
  {
    id: 5,
    code: "TCV05",
    name: "Terma solar completa de 15 tubos (150L) de acero inox 316 interno + acero galbanizado pintado externo; Ø58×1800 mm",
    otherNames: "- Terma Solar de 150L Tapa Verde\n- Terma Solar de 15 Tubos Tapa Verde",
    fotos: "",
    description:
      "- Termotanque + Caja de Tubos + Estructura\n- Termotanque de acero inox 316 interno y acero galbanizado pintado externo\n- Termotanque no presurizado\n- Aislante térmico de poliuretano entre el tanque interno y externo\n- Estructura de acero inoxidable",
    price: "1,780.00",
    otherPrices: "1,700.00",
    notes: "- Se requiere de boya cuando no tiene tanque elevado (Rotoplas)\n- El precio normal es con boya\n- El otro precio es sin boya",
    stock: 4,
    category: "Termas Solares",
  },
  {
    id: 6,
    code: "TCV06",
    name: "Terma solar completa de 18 tubos (180L) de acero inox 316 interno + acero galbanizado pintado externo; Ø58×1800 mm",
    otherNames: "- Terma Solar de 180L Tapa Verde\n- Terma Solar de 18 Tubos Tapa Verde",
    fotos: "",
    description:
      "- Termotanque + Caja de Tubos + Estructura\n- Termotanque de acero inox 316 interno y acero galbanizado pintado externo\n- Termotanque no presurizado\n- Aislante térmico de poliuretano entre el tanque interno y externo\n- Estructura de acero inoxidable",
    price: "1,980.00",
    otherPrices: "1,900.00",
    notes: "- Se requiere de boya cuando no tiene tanque elevado (Rotoplas)\n- El precio normal es con boya\n- El otro precio es sin boya",
    stock: 3,
    category: "Termas Solares",
  },
  {
    id: 7,
    code: "TCV07",
    name: "Terma solar completa de 20 (200L) tubos de acero inox 316 interno + acero galbanizado pintado externo; Ø58×1800 mm",
    otherNames: "- Terma Solar de 200L Tapa Verde\n- Terma Solar de 20 Tubos Tapa Verde",
    fotos: "",
    description:
      "- Termotanque + Caja de Tubos + Estructura\n- Termotanque de acero inox 316 interno y acero galbanizado pintado externo\n- Termotanque no presurizado\n- Aislante térmico de poliuretano entre el tanque interno y externo\n- Estructura de acero inoxidable",
    price: "2,180.00",
    otherPrices: "2,100.00",
    notes: "- Se requiere de boya cuando no tiene tanque elevado (Rotoplas)\n- El precio normal es con boya\n- El otro precio es sin boya",
    stock: 7,
    category: "Termas Solares",
  },
  {
    id: 8,
    code: "TCV08",
    name: "Terma solar completa de 24 (240L) tubos de acero inox 316 interno + acero galbanizado pintado externo; Ø58×1800 mm",
    otherNames: "- Terma Solar de 240L Tapa Verde\n- Terma Solar de 24 Tubos Tapa Verde",
    fotos: "",
    description:
      "- Termotanque + Caja de Tubos + Estructura\n- Termotanque de acero inox 316 interno y acero galbanizado pintado externo\n- Termotanque no presurizado\n- Aislante térmico de poliuretano entre el tanque interno y externo\n- Estructura de acero inoxidable",
    price: "2,480.00",
    otherPrices: "2,400.00",
    notes: "- Se requiere de boya cuando no tiene tanque elevado (Rotoplas)\n- El precio normal es con boya\n- El otro precio es sin boya",
    stock: 2,
    category: "Termas Solares",
  },
  {
    id: 9,
    code: "TCV09",
    name: "Terma solar completa de 30 (300L) tubos de acero inox 316 interno + acero galbanizado pintado externo; Ø58×1800 mm",
    otherNames: "- Terma Solar de 300L Tapa Verde\n- Terma Solar de 30 Tubos Tapa Verde",
    fotos: "",
    description:
      "- Termotanque + Caja de Tubos + Estructura\n- Termotanque de acero inox 316 interno y acero galbanizado pintado externo\n- Termotanque no presurizado\n- Aislante térmico de poliuretano entre el tanque interno y externo\n- Estructura de acero inoxidable",
    price: "2,880.00",
    otherPrices: "2,800.00",
    notes: "- Se requiere de boya cuando no tiene tanque elevado (Rotoplas)\n- El precio normal es con boya\n- El otro precio es sin boya",
    stock: 1,
    category: "Termas Solares",
  },
];
